### ISSUE TITLE
‼️ No such module 'AppSyncRealTimeClient' / Type 'StarscreamAdapter' does not conform to protocol 'WebSocketDelegate'

### ISSUE THREAD

**Issue by atierian** [aws-amplify/amplify-swift#3164]
## SPM
[AppSyncRealTimeClient v3.1.1](https://github.com/aws-amplify/aws-appsync-realtime-client-ios/releases/tag/3.1.1) release is complete.

If you're using SPM with Amplify iOS v1 or Amplify Swift v2, this issue should now be resolved. If you're still seeing the error, please select `File > Packages > Update to Latest Package Versions` and ensure that AppSyncRealTimeClient is using 3.1.1.

## CocoaPods
[AppSyncRealTimeClient v3.1.1](https://cocoapods.org/pods/AppSyncRealTimeClient) release is complete

If you're using CocoaPods with Amplify iOS v1, this issue should new be resolved. If you're still seeing the error, please try running `pod install --repo-update` to ensure you have the most recent version. If that doesn't work, try deleting derived data. If that still doesn't work, please let us know by opening an issue. Thanks!

-----

Compiler error preventing Amplify Swift from being built.

This can also manifest as:
```
Type 'StarscreamAdapter' does not conform to protocol 'WebSocketDelegate'
Switch must be exhaustive
```

**Comment by atierian** [comment]
## SPM
If you're using SPM with Amplify iOS v1 or Amplify Swift v2, this issue should now be resolved. If you're still seeing the error, please select `File > Packages > Update to Latest Package Versions` and ensure that AppSyncRealTimeClient is using 3.1.1.

## CocoaPods
[Release in progress](https://github.com/aws-amplify/aws-appsync-realtime-client-ios/actions/runs/5918929829)

**Comment by stephenjen** [comment]
I have the same issue.  @atierian, is this closed because it has been fixed?

**Comment by atierian** [comment]
It is fixed, yes. Are you still experiencing this issue after following the instructions listed in the issue description?

**Comment by stephenjen** [comment]
Sorry, I just saw it.  I'm at amplify_flutter: ^0.6.12, would I need to upgrade to 1.0 to see this change?

**Comment by atierian** [comment]
Based on the dependency versioning rules, running `pod install --repo-update` should work for the version of Amplify Flutter you're using.

**Comment by stephenjen** [comment]
Hmm, still getting the error.  To be sure, these are all the Amplify related items in my pubspec:

  amplify_flutter: ^0.6.12
  amplify_datastore: ^0.6.12
  amplify_auth_cognito: ^0.6.12
  amplify_authenticator: ^0.2.4
  amplify_api: ^0.6.12
  amplify_storage_s3: ^0.6.12

**Comment by hidekazu-kato** [comment]
It seems that the issue is still not fixed even after updating to AppSyncRealTimeClient v3.1.1. Please provide assistance.

・Operating Environment:
macOS Sonoma 14.0
Xcode 15.0
Swift Package Manager
Amplify 2.19.0
AppSyncRealTimeClient v3.1.1

・Error Message:
Type 'StarscreamAdapter' does not conform to protocol 'WebSocketDelegate'
Switch must be exhaustive

<img width="386" alt="Screenshot 2023-10-03 at 8 37 41" src="https://github.com/aws-amplify/amplify-swift/assets/23710585/b19e5bd5-f48d-407f-a7db-55ac95677326">
<img width="230" alt="Screenshot 2023-10-03 at 8 37 22" src="https://github.com/aws-amplify/amplify-swift/assets/23710585/62b06422-82c1-49d1-805c-c2600da80ce2">

**Comment by stephenjen** [comment]
I ended up having to upgrade flutter to 3.13.5, in addition to upgrading my packages to ^1.0.0:

  amplify_flutter: ^1.0.0
  amplify_datastore: ^1.0.0
  amplify_auth_cognito: ^1.0.0
  amplify_authenticator: ^1.0.0
  amplify_api: ^1.0.0
  amplify_storage_s3: ^1.0.0

**Comment by atierian** [comment]
Thanks for letting us know @stephenjen, glad to hear it's working for you with Flutter now.

@hidekazu-kato that's likely due to an Xcode / SPM cache issue from a previous build. I recommend deleting derived data and SPM caches.

**Comment by ibrotutic** [comment]
Hey all, we just ran into this issue in our builds and I am working on fixing it. We depend on AWSAppSync:3.6.2, which depends on AppSyncRealTimeclient:3.0.0. I tried bumping the real time client to 3.1.1, and got the below problem. How do I resolve this in the Podfile?

INFO: Resolving dependencies of `Podfile`
INFO: [!] CocoaPods could not find compatible versions for pod "AppSyncRealTimeClient":
     In Podfile:
          INFO:     AWSAppSync (~> 3.6.2) was resolved to 3.6.2, which depends on
          INFO:       AppSyncRealTimeClient (~> 3.0.0)
          INFO:     AppSyncRealTimeClient (~> 3.1.1)
INFO: Specs satisfying the `AppSyncRealTimeClient (~> 3.1.1), AppSyncRealTimeClient (~> 3.0.0)` dependency were found, but they required a higher minimum deployment target.

**Comment by atierian** [comment]
Thanks for reporting this @ibrotutic. 

The issue you're seeing is specific to [awslabs/aws-mobile-appsync-sdk-ios](https://github.com/awslabs/aws-mobile-appsync-sdk-ios) and not related to Amplify. For future reference @ibrotutic and I discussed and resolved this outside of GitHub. 

For anyone reading this that encountered this error, please open a new issue. Thanks!

**Comment by lindrrow-gh** [comment]
Hi @atierian, are there any ways to solve this issue. It seems that **AppSyncRealTimeClient** is forced to use **starscream 4.0.4** for later versions but my project uses **starscream 4.0.6** due to other pod package dependency. 

FYI, I am using Flutter.

**Comment by willnix86** [comment]
I'm still seeing this issue with the latest version of amplify-swift. Package.resolved shows that version 3.1.0 is still being used. I'm using Tuist for this project, have tried deleting package caches and derived data, but still don't see 3.1.1 being used.

```
{
  "pins" : [
    {
      "identity" : "amplify-swift",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/aws-amplify/amplify-swift",
      "state" : {
        "revision" : "c2fb1c076a9f0c7bcd56bccba355ac85ab109f94",
        "version" : "2.28.0"
      }
    },
    {
      "identity" : "amplify-swift-utils-notifications",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/aws-amplify/amplify-swift-utils-notifications.git",
      "state" : {
        "revision" : "959eec669ba97c7d923b963c3e66ca8a0b2737f6",
        "version" : "1.1.1"
      }
    },
    {
      "identity" : "aws-appsync-realtime-client-ios",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/aws-amplify/aws-appsync-realtime-client-ios.git",
      "state" : {
        "revision" : "b036e83716789c13a3480eeb292b70caa54114f2",
        "version" : "3.1.0"
      }
    },
```

**Comment by lawmicha** [comment]
Hi @lindrrow-gh, we will be upgrading Startscream to 4.0.6 in the upcoming release https://github.com/aws-amplify/aws-appsync-realtime-client-ios/pull/152. This will be released most likely in version 3.2.0. It should work for you but it will be a problem again if you upgrade starscream to a newer version. Please open an issue with us again if you are looking to use a newer version of starscream and we'll evaluate our dependency upgrade on starscream as well.

**Comment by lawmicha** [comment]
Hi @willnix86, Amplify Swift's latest version 2.28.0 https://github.com/aws-amplify/amplify-swift/blob/2.28.0/Package.swift#L13 uses AppSyncRealTimeClient `from: 3.0.0` so it's picking up 3.1.0 but not 3.1.2 (current latest) probably means something is going on with it being pinned. Feel free to open a new issue over in the Amplify Swift repo with your details (https://github.com/aws-amplify/amplify-swift/issues/new?assignees=&labels=&projects=&template=bug_report.yaml) for us to better track it, since this issue is closed now. Also reaching to Tuist community may help as well.
